apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-lab-ingress
  namespace: web-lab
  labels:
    app: web
    env: lab
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: web.lab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-green-svc
                port:
                  number: 80
          - path: /blue
            pathType: Prefix
            backend:
              service:
                name: web-blue-svc
                port:
                  number: 80
          - path: /green
            pathType: Prefix
            backend:
              service:
                name: web-green-svc
                port:
                  number: 80
